version: "3.9"

services:
  mailsender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailsender-dhl
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
